language: python
python:
  - "3.4"
  - "3.5"

sudo: required
services:
  - docker

install:
  - "pip install -r app/requirements.txt"
  - "pip install -r app/test-requirements.txt"

script: "nosetests app/"

deploy:
  provider: script
  script: ./docker_push.sh
  on:
    branch: master

notifications:
  email:
    on_failure: change
